spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
        routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
server:
  port: 9090

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
